### ISSUE TITLE
Stiff solvers do not work with SLVector

### ISSUE THREAD

**Issue by istvankleijn** [JuliaDiffEq/LabelledArrays.jl#41] opened 2019-01-31 15:53 UTC
Almost identical to #14, I find errors (`type MArray has no field ...`) when trying to use stiff solvers with static arrays (`SLVector` instead of #14's `LVector`).

```julia
using LabelledArrays  # v0.4.0
using OrdinaryDiffEq  # v4.21.0

LorenzVector = @SLVector (:x,:y,:z)
LorenzParameterVector = @SLVector (:σ,:ρ,:β)

function f(u, p, t)
  x = p.σ*(u.y - u.x)
  y = u.x*(p.ρ - u.z) - u.y
  z = u.x*u.y - p.β*u.z
  return LorenzVector(x, y, z)
end

u0 = LorenzVector(1.0, 0.0, 0.0)
p = LorenzParameterVector(10.0, 28.0, 8/3)
tspan = (0.0, 10.0)
prob = ODEProblem(f, u0, tspan, p)
sol = solve(prob, Rodas5())  # type MArray has no field y
```

**Comment by ChrisRackauckas** [comment] 2019-01-31 16:48
The MWE is:

```julia
using LabelledArrays 
LorenzVector = @SLVector (:x,:y,:z)
u0 = LorenzVector(1.0, 0.0, 0.0)
similar(u0)
```

We are missing the `similar` definition on `SLVector` which would make this work.

**Comment by devmotion** [comment] 2019-02-04 13:59
Unfortunately even with https://github.com/JuliaDiff/DiffResults.jl/pull/7 and https://github.com/JuliaDiff/ForwardDiff.jl/pull/383 this example still fails with the error message
```julia
ERROR: AssertionError: length(NewSize) == N
Stacktrace:
 [1] similar_type(::Type{SLArray{Tuple{3},Float64,1,3,(:x, :y, :z)}}, ::Type{Float64}, ::StaticArrays.Size{(3, 3)}) at /home/david/.julia/dev/LabelledArrays/src/slarray.jl:57
```
The problem is that LabelledArrays currently does not allow to change the size when computing a similar type which however would be required in https://github.com/JuliaDiff/DiffResults.jl/pull/7/files#diff-63e7ce79ad9aec78ddbf088758294df7R95.

**Comment by devmotion** [comment] 2019-02-23 10:57
This error is fixed on master using the latest version of ForwardDiff and PR https://github.com/JuliaArrays/StaticArrays.jl/pull/595 (which fixes the current test failures).

**Comment by devmotion** [comment] 2019-02-28 08:18
I can confirm that the example above does not error anymore if you use ForwardDiff 0.10.3, StaticArrays 0.10.3, and the master branch of LabelledArrays.

**Closed** 2019-02-28 13:58 UTC
